apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-server
spec:
  selector:
    matchLabels:
      app: api-server
  replicas: {{ .Values.apiServer.replicaCount }}
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: {{ .Values.apiServer.image }}
        imagePullPolicy: Always
        env:
        - name: BUGS_ENV
          value: {{ quote .Values.environment }}
        - name: REDIS_HOST
          value: {{ quote .Values.database.host }}
        ports:
        - containerPort: 80
          name: api-server-port
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-svc
  namespace: bugs 
  labels:
    app: api-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: api-server-port 
    name: api-server-svc-port
  selector:
    app: api-server
